[PHP]

display_errors = On
display_startup_errors = On
error_reporting = E_ALL

memory_limit = 256M

upload_max_filesize = 100M
post_max_size = 100M

max_execution_time = 300
max_input_time = 300

date.timezone = Asia/Manila

session.save_handler = files

max_file_uploads = 20